[build]
  functions = "netlify/functions"
  publish = "public"

[functions."estado"]
  included_files = ["netlify/functions/servidores.json"]

[[plugins]]
package = "netlify-plugin-is-website-vulnerable"  # Ejemplo, no agregues el vulnerable
